### ISSUE TITLE
Option for static CDN file names

### ISSUE THREAD

**Issue by thebells1111** [lovvtide/satellite-web#7]
This would be great for hosting podcasting and Music 2.0 files. However, for it to work with the directories, the RSS file would need to be able to be uploaded and the file remains the same. So something like `feed.xml` is uploaded and given the file on the cdn of `https://cdn.satellite.earth/a52513f18846594e27244d41510054ee81fa2363d5334970101f1ccc74671085.xml`. Later, a new episode is added, so the 'feed.xml' file is updated with the new info. When it is the cdn file needs to remain the same instead of generating a new file. This way a directory is always looking at `https://cdn.satellite.earth/a52513f18846594e27244d41510054ee81fa2363d5334970101f1ccc74671085.xml` but the contents of the file could change as the podcaster updates their feed.

**Comment by lovvtide** [comment]
Hi, sorry for the slow response — at this what you're describing is not feasible because the url path is the sha256 hash of the file. This would be hard to change, since the sha256 hash standard is baked into NIP-94, which the CDN is designed to be compatible with. I have considered adding RSS support to Satellite, however, if/when I do that it will be a standalone product.
